"use client";

import { useEffect, useMemo, useState } from "react";
import { BookOpenText, Check, FolderKanban, LoaderCircle, Package, Pencil, Plus, Save, Search, Trash2, Trees } from "lucide-react";

type Resource = "plants" | "products" | "blogs" | "projects";
type Item = Record<string, string | number | boolean | null>;
type Field = { key: string; label: string; type?: "text" | "number" | "textarea" | "checkbox" | "select" | "url"; options?: string[]; required?: boolean; hint?: string };
type Config = { label: string; singular: string; icon: typeof Trees; titleKey: string; subtitleKey: string; fields: Field[]; empty: Item };

const configs: Record<Resource, Config> = {
  plants: { label: "Plants & trees", singular: "plant", icon: Trees, titleKey: "commonName", subtitleKey: "botanicalName", empty: { id:"",commonName:"",botanicalName:"",region:"",ecologicalRole:"",waterRequirement:"Moderate",plantSize:"60–90 cm",price:0,stockStatus:"Available",imageUrl:"",description:"",featured:false,active:true,sortOrder:0 }, fields: [
    {key:"commonName",label:"Common name",required:true},{key:"botanicalName",label:"Botanical name",required:true},{key:"id",label:"URL slug",required:true,hint:"Lowercase letters, numbers and hyphens"},{key:"region",label:"Native region",required:true},{key:"ecologicalRole",label:"Ecological role",required:true},{key:"waterRequirement",label:"Water requirement",type:"select",options:["Low","Moderate","High"]},{key:"plantSize",label:"Plant size",required:true},{key:"price",label:"Indicative price (₹)",type:"number"},{key:"stockStatus",label:"Stock status",type:"select",options:["Available","Low stock","Contract grow"]},{key:"imageUrl",label:"Image URL",type:"url"},{key:"description",label:"Description",type:"textarea"},{key:"sortOrder",label:"Display order",type:"number"},{key:"featured",label:"Featured plant",type:"checkbox"},{key:"active",label:"Visible on website",type:"checkbox"},
  ]},
  products: { label: "Local products", singular: "product", icon: Package, titleKey: "name", subtitleKey: "producer", empty: { id:"",name:"",category:"",producer:"",location:"",price:0,badge:"",imageUrl:"",description:"",featured:false,active:true,sortOrder:0 }, fields: [
    {key:"name",label:"Product name",required:true},{key:"id",label:"URL slug",required:true},{key:"category",label:"Category",required:true},{key:"producer",label:"Producer or group",required:true},{key:"location",label:"Location",required:true},{key:"price",label:"Price (₹)",type:"number"},{key:"badge",label:"Product badge"},{key:"imageUrl",label:"Image URL",type:"url"},{key:"description",label:"Description",type:"textarea"},{key:"sortOrder",label:"Display order",type:"number"},{key:"featured",label:"Featured product",type:"checkbox"},{key:"active",label:"Visible on website",type:"checkbox"},
  ]},
  blogs: { label: "Blogs & guides", singular: "article", icon: BookOpenText, titleKey: "title", subtitleKey: "category", empty: { id:"",title:"",excerpt:"",body:"",category:"Restoration guides",readTime:"5 min",coverImageUrl:"",status:"Draft",featured:false }, fields: [
    {key:"title",label:"Article title",required:true},{key:"id",label:"URL slug",required:true},{key:"category",label:"Category",required:true},{key:"readTime",label:"Reading time",required:true},{key:"excerpt",label:"Short summary",type:"textarea",required:true},{key:"body",label:"Article content",type:"textarea",required:true},{key:"coverImageUrl",label:"Cover image URL",type:"url"},{key:"status",label:"Publication status",type:"select",options:["Draft","Published"]},{key:"featured",label:"Featured article",type:"checkbox"},
  ]},
  projects: { label: "Projects & impact", singular: "project", icon: FolderKanban, titleKey: "title", subtitleKey: "location", empty: { id:"",title:"",location:"",area:"",projectType:"",status:"Baseline assessment",speciesCount:0,period:"24 months",progress:0,summary:"",imageUrl:"",featured:false,published:true,sortOrder:0 }, fields: [
    {key:"title",label:"Project title",required:true},{key:"id",label:"URL slug",required:true},{key:"location",label:"Location",required:true},{key:"area",label:"Area",required:true},{key:"projectType",label:"Project type",required:true},{key:"status",label:"Current status",required:true},{key:"speciesCount",label:"Native species count",type:"number"},{key:"period",label:"Project period",required:true},{key:"progress",label:"Progress (%)",type:"number"},{key:"summary",label:"Project summary",type:"textarea",required:true},{key:"imageUrl",label:"Image URL",type:"url"},{key:"sortOrder",label:"Display order",type:"number"},{key:"featured",label:"Featured project",type:"checkbox"},{key:"published",label:"Visible on website",type:"checkbox"},
  ]},
};

function slugify(value: string) {
  return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,100);
}

export function AdminContentManager() {
  const [resource,setResource]=useState<Resource>("plants");
  const [items,setItems]=useState<Item[]>([]);
  const [form,setForm]=useState<Item>(configs.plants.empty);
  const [editing,setEditing]=useState<string | null>(null);
  const [query,setQuery]=useState("");
  const [busy,setBusy]=useState(true);
  const [notice,setNotice]=useState("");
  const config=configs[resource];
  const EmptyIcon=config.icon;

  async function load(nextResource=resource){setBusy(true);setNotice("");try{const response=await fetch(`/api/admin/content?resource=${nextResource}`);const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Unable to load content.");setItems(payload.items??[])}catch(error){setNotice(error instanceof Error?error.message:"Unable to load content.")}finally{setBusy(false)}}
  useEffect(()=>{let active=true;fetch(`/api/admin/content?resource=${resource}`).then(async response=>({ok:response.ok,payload:await response.json()})).then(({ok,payload})=>{if(!active)return;if(!ok)throw new Error(payload.error??"Unable to load content.");setItems(payload.items??[])}).catch(error=>{if(active)setNotice(error instanceof Error?error.message:"Unable to load content.")}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[resource]);
  const visible=useMemo(()=>{const needle=query.trim().toLowerCase();return needle?items.filter(item=>Object.values(item).some(value=>String(value??"").toLowerCase().includes(needle))):items},[items,query]);

  function choose(next:Resource){setBusy(true);setResource(next);setForm(configs[next].empty);setEditing(null);setQuery("");setNotice("")}
  function change(field:Field,value:string|boolean){const parsed=field.type==="number"?Number(value):value;setForm(current=>{const next={...current,[field.key]:parsed};if(!editing&&field.key===config.titleKey&&!current.id)next.id=slugify(String(value));return next})}
  function edit(item:Item){setEditing(String(item.id));setForm({...config.empty,...item});setNotice("");window.scrollTo({top:0,behavior:"smooth"})}
  function reset(){setEditing(null);setForm(config.empty);setNotice("")}
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setNotice("");try{const response=await fetch("/api/admin/content",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource,id:editing,item:form})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Content could not be saved.");await load();setEditing(null);setForm(config.empty);setNotice(`${config.singular[0].toUpperCase()+config.singular.slice(1)} ${editing?"updated":"created"} successfully.`)}catch(error){setNotice(error instanceof Error?error.message:"Content could not be saved.")}finally{setBusy(false)}}
  async function remove(item:Item){if(!window.confirm(`Permanently remove “${String(item[config.titleKey])}”?`))return;setBusy(true);setNotice("");try{const response=await fetch(`/api/admin/content?resource=${resource}&id=${encodeURIComponent(String(item.id))}`,{method:"DELETE"});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Content could not be removed.");await load();setNotice("Item removed.")}catch(error){setNotice(error instanceof Error?error.message:"Content could not be removed.")}finally{setBusy(false)}}

  return <section className="admin-content-manager"><div className="admin-resource-tabs" aria-label="Content types">{(Object.keys(configs) as Resource[]).map(key=>{const Icon=configs[key].icon;return <button key={key} className={resource===key?"active":""} onClick={()=>choose(key)}><Icon/>{configs[key].label}</button>})}</div>{notice&&<div className={/could not|unable|invalid|required/i.test(notice)?"admin-notice error":"admin-notice"}><Check/>{notice}</div>}<div className="admin-content-layout"><form className="admin-content-form" onSubmit={save}><div className="widget-head"><div><p className="eyebrow">{editing?"Edit existing":"Create new"}</p><h3>{editing?`Edit ${config.singular}`:`Add ${config.singular}`}</h3></div>{editing&&<button type="button" className="text-button" onClick={reset}>Cancel edit</button>}</div><div className="form-grid">{config.fields.map(field=><label key={field.key} className={field.type==="textarea"?"full":""}>{field.type==="checkbox"?<span className="admin-check"><input type="checkbox" checked={Boolean(form[field.key])} onChange={event=>change(field,event.target.checked)}/>{field.label}</span>:<><span>{field.label}</span>{field.type==="textarea"?<textarea required={field.required} value={String(form[field.key]??"")} onChange={event=>change(field,event.target.value)}/>:field.type==="select"?<select value={String(form[field.key]??"")} onChange={event=>change(field,event.target.value)}>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:<input required={field.required} type={field.type==="number"?"number":"text"} min={field.type==="number"?0:undefined} value={String(form[field.key]??"")} onChange={event=>change(field,event.target.value)}/>} {field.hint&&<small>{field.hint}</small>}</>}</label>)}</div><button className="button button-earth" disabled={busy}>{busy?<LoaderCircle className="spin"/>:editing?<Save/>:<Plus/>}{editing?"Save changes":`Add ${config.singular}`}</button></form><div className="admin-content-list"><div className="admin-content-toolbar"><div><p className="eyebrow">Content library</p><h3>{config.label}</h3></div><label className="search-box small"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={`Search ${config.label.toLowerCase()}`}/></label></div>{busy&&items.length===0?<p>Loading…</p>:visible.length===0?<div className="portal-empty"><EmptyIcon/><p>No matching content yet.</p></div>:visible.map(item=><article key={String(item.id)}><div><b>{String(item[config.titleKey])}</b><span>{String(item[config.subtitleKey]??item.id)}</span><small>{String(item.id)}</small></div><div className="admin-content-row-actions"><button onClick={()=>edit(item)}><Pencil/> Edit</button><button className="danger" onClick={()=>remove(item)}><Trash2/> Delete</button></div></article>)}</div></div></section>;
}
