"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useState } from "react";
import { Check, ExternalLink, FileImage, Globe2, LoaderCircle, Save, ShieldCheck, Trash2, UploadCloud, Users } from "lucide-react";
import { defaultSiteContent, type SiteContent } from "@/lib/site-content";

type MediaAsset={id:string;filename:string;url:string;altText:string;size:number;createdAt:string};
type Member={id:string;email:string;name:string;organisation:string;role:"admin"|"client"|"partner"|"field";status:"Active"|"Inactive"};
type Tab="website"|"media"|"users"|"portals";

export default function AdminControlCentre(){
  const [tab,setTab]=useState<Tab>("website");const [content,setContent]=useState<SiteContent>(defaultSiteContent);const [assets,setAssets]=useState<MediaAsset[]>([]);const [members,setMembers]=useState<Member[]>([]);const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [member,setMember]=useState({email:"",name:"",organisation:"",role:"client"});
  async function loadAssets(){const response=await fetch("/api/admin/media");const payload=await response.json();if(response.ok)setAssets(payload.assets??[])}
  async function loadMembers(){const response=await fetch("/api/admin/members");const payload=await response.json();if(response.ok)setMembers(payload.members??[])}
  useEffect(()=>{let active=true;Promise.all([fetch("/api/site-content").then(r=>r.json()),fetch("/api/admin/media").then(r=>r.json()),fetch("/api/admin/members").then(r=>r.json())]).then(([contentPayload,mediaPayload,memberPayload])=>{if(!active)return;setContent(contentPayload.content??defaultSiteContent);setAssets(mediaPayload.assets??[]);setMembers(memberPayload.members??[])});return()=>{active=false}},[]);
  async function saveContent(event:React.FormEvent){event.preventDefault();setBusy(true);setNotice("");const response=await fetch("/api/site-content",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({content})});const payload=await response.json();setNotice(response.ok?"Website content published successfully.":payload.error??"Content could not be saved.");setBusy(false)}
  async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setNotice("");const response=await fetch("/api/admin/media",{method:"POST",body:new FormData(event.currentTarget)});const payload=await response.json();if(response.ok){event.currentTarget.reset();await loadAssets();setNotice("Image uploaded to the media library.")}else setNotice(payload.error??"Upload failed.");setBusy(false)}
  async function removeAsset(asset:MediaAsset){if(!window.confirm(`Remove ${asset.filename} from the media library?`))return;setBusy(true);const response=await fetch(`/api/admin/media?id=${asset.id}`,{method:"DELETE"});if(response.ok){if(content.heroImageUrl===asset.url)setContent({...content,heroImageUrl:defaultSiteContent.heroImageUrl});await loadAssets();setNotice("Image removed.")}setBusy(false)}
  async function saveMember(event:React.FormEvent){event.preventDefault();setBusy(true);setNotice("");const response=await fetch("/api/admin/members",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(member)});const payload=await response.json();if(response.ok){setMember({email:"",name:"",organisation:"",role:"client"});await loadMembers();setNotice("Portal user saved. They can sign in directly to their assigned workspace.")}else setNotice(payload.error??"User could not be saved.");setBusy(false)}
  async function updateMember(row:Member,patch:Partial<Member>){setBusy(true);const next={...row,...patch};const response=await fetch("/api/admin/members",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:next.id,role:next.role,status:next.status})});if(response.ok)await loadMembers();setBusy(false)}
  const set=(key:keyof SiteContent)=>(event:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>setContent({...content,[key]:event.target.value});
  return <section className="admin-control-centre"><div className="admin-control-head"><div><p className="eyebrow">Website control centre</p><h2>Manage Prachurja</h2><p>Edit public content, upload images and decide who can access each operational workspace.</p></div><a className="button button-secondary" href="/" target="_blank">View live website <ExternalLink/></a></div><nav className="admin-tabs" aria-label="Administration sections">{[["website",Globe2,"Website"],["media",FileImage,"Media library"],["users",Users,"Users & roles"],["portals",ShieldCheck,"Portal previews"]].map(([id,Icon,label])=>{const I=Icon as typeof Globe2;return <button className={tab===id?"active":""} onClick={()=>{setTab(id as Tab);setNotice("")}} key={String(id)}><I/>{String(label)}</button>})}</nav>{notice&&<div className={notice.includes("could not")||notice.includes("failed")?"admin-notice error":"admin-notice"}><Check/>{notice}</div>}
  {tab==="website"&&<form className="admin-editor" onSubmit={saveContent}><div className="admin-editor-main"><p className="eyebrow">Homepage</p><h3>Hero content</h3><div className="form-grid"><label><span>Eyebrow</span><input value={content.heroEyebrow} onChange={set("heroEyebrow")}/></label><label><span>Headline line 1</span><input value={content.heroTitleLine1} onChange={set("heroTitleLine1")}/></label><label><span>Highlighted line</span><input value={content.heroTitleAccent} onChange={set("heroTitleAccent")}/></label><label><span>Headline line 3</span><input value={content.heroTitleLine3} onChange={set("heroTitleLine3")}/></label><label className="full"><span>Hero description</span><textarea value={content.heroDescription} onChange={set("heroDescription")}/></label><label className="full"><span>Hero image URL</span><input value={content.heroImageUrl} onChange={set("heroImageUrl")} placeholder="/api/media/…"/></label></div><p className="eyebrow admin-subhead">Footer and contact</p><div className="form-grid"><label className="full"><span>Footer description</span><textarea value={content.footerDescription} onChange={set("footerDescription")}/></label><label><span>Contact email</span><input type="email" value={content.contactEmail} onChange={set("contactEmail")} placeholder="hello@example.org"/></label><label><span>Contact phone</span><input value={content.contactPhone} onChange={set("contactPhone")} placeholder="+91 …"/></label><label className="full"><span>Service location</span><input value={content.officeLocation} onChange={set("officeLocation")}/></label></div><button className="button button-earth" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Save/>} Publish website changes</button></div><aside className="admin-live-preview"><span>Live preview</span><div className="admin-hero-preview" style={{backgroundImage:`linear-gradient(90deg,rgba(10,45,35,.88),rgba(10,45,35,.25)),url(${content.heroImageUrl})`}}><small>{content.heroEyebrow}</small><h3>{content.heroTitleLine1}<br/><em>{content.heroTitleAccent}</em><br/>{content.heroTitleLine3}</h3><p>{content.heroDescription}</p></div><p>Changes become public when you press Publish.</p></aside></form>}
  {tab==="media"&&<div className="admin-media-layout"><form className="admin-upload" onSubmit={upload}><UploadCloud/><h3>Upload an image</h3><p>JPG, PNG or WebP · maximum 8 MB. Add useful alternative text for accessibility.</p><input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/><label><span>Alternative text</span><input name="altText" required minLength={3} placeholder="Describe the image"/></label><button className="button button-primary" disabled={busy}>{busy?"Uploading…":"Upload to library"}</button></form><div className="admin-media-grid">{assets.length===0?<div className="portal-empty"><FileImage/><p>No uploaded media yet.</p></div>:assets.map(asset=><article key={asset.id}><img src={asset.url} alt={asset.altText}/><div><b>{asset.filename}</b><span>{(asset.size/1024/1024).toFixed(2)} MB</span><p>{asset.altText}</p><div><button onClick={()=>{setContent({...content,heroImageUrl:asset.url});setTab("website");setNotice("Image selected. Publish website changes to make it live.")}}>Use as hero</button><button className="danger" onClick={()=>removeAsset(asset)}><Trash2/> Remove</button></div></div></article>)}</div></div>}
  {tab==="users"&&<div className="admin-users-layout"><form className="admin-user-form" onSubmit={saveMember}><p className="eyebrow">Direct access</p><h3>Add a portal user</h3><p>No request form is needed. Assign the person and they can sign in directly.</p><label><span>Email</span><input type="email" required value={member.email} onChange={e=>setMember({...member,email:e.target.value})}/></label><label><span>Name</span><input required minLength={2} value={member.name} onChange={e=>setMember({...member,name:e.target.value})}/></label><label><span>Organisation</span><input required minLength={2} value={member.organisation} onChange={e=>setMember({...member,organisation:e.target.value})}/></label><label><span>Workspace</span><select value={member.role} onChange={e=>setMember({...member,role:e.target.value})}><option value="client">Client portal</option><option value="partner">Partner portal</option><option value="field">Field portal</option><option value="admin">Administrator</option></select></label><button className="button button-primary" disabled={busy}>Save portal user</button></form><div className="admin-member-list"><div><p className="eyebrow">Access directory</p><h3>Users and roles</h3></div>{members.length===0?<div className="portal-empty"><Users/><p>No database-managed users yet. Environment administrators remain active.</p></div>:members.map(row=><article key={row.id}><div><b>{row.name}</b><span>{row.email}</span><small>{row.organisation}</small></div><select value={row.role} disabled={busy} onChange={e=>updateMember(row,{role:e.target.value as Member["role"]})}><option value="admin">Admin</option><option value="client">Client</option><option value="partner">Partner</option><option value="field">Field</option></select><button className={row.status==="Active"?"status-active":""} disabled={busy} onClick={()=>updateMember(row,{status:row.status==="Active"?"Inactive":"Active"})}>{row.status}</button></article>)}</div></div>}
  {tab==="portals"&&<div className="admin-portal-grid">{[["Client portal","Projects, assessments, reports and next actions.","/client"],["Partner portal","Inventory batches, supply capacity and approvals.","/partner-portal"],["Field portal","Field assignments, quantities, maintenance and issues.","/field"],["Public website","Customer-facing Prachurja experience.","/"]].map(([title,copy,href])=><a href={href} key={href} target="_blank"><ShieldCheck/><span><b>{title}</b><p>{copy}</p></span><ExternalLink/></a>)}</div>}
  </section>
}
