import { ArrowRight, BookOpen, ClipboardCheck, Leaf, PackageCheck, ShieldCheck } from "lucide-react";
import { articles } from "@/lib/mock-data";

export function BlogPage() {
  return <main><section className="page-hero"><div className="shell"><p className="eyebrow">Prachurja journal</p><h1>Field notes for better restoration decisions</h1><p>Practical thinking on native plants, soil, water, long-term maintenance and community participation.</p></div></section><section className="section"><div className="shell blog-layout"><article className="blog-feature"><span><BookOpen/></span><p className="eyebrow">Featured · Restoration fundamentals</p><h2>Why a restoration plan begins before the plant list</h2><p>A baseline, reference ecosystem and maintenance pathway determine whether planting is useful—and how recovery should be measured.</p><a className="button button-primary" href="/knowledge">Read in the knowledge centre <ArrowRight/></a></article><div className="blog-grid">{articles.map(([eyebrow,title,time,category]) => <article key={title}><span>{category}</span><p className="eyebrow">{eyebrow} · {time}</p><h2>{title}</h2><p>Plain-language guidance connecting ecological principles with practical site decisions.</p><a href="/knowledge">Read article <ArrowRight/></a></article>)}</div></div></section></main>;
}

const content = {
  privacy: { eyebrow: "Privacy", title: "Your information should serve your enquiry—not become a product.", icon: ShieldCheck, sections: [["Information we collect","Assessment, contact, partnership and portal forms collect only the details needed to review, respond to and manage your request."],["How it is used","Information is used for service delivery, operational follow-up, role-based portal access and necessary record keeping."],["Storage and access","Operational records are stored in the Prachurja platform database and restricted according to administrative roles."],["Your choices","You may ask Prachurja to correct or remove information where retention is not legally or operationally required."]] },
  terms: { eyebrow: "Terms of use", title: "Clear expectations for ecological information and enquiries.", icon: ClipboardCheck, sections: [["Catalogue information","Plant availability, prices, provenance and delivery estimates are indicative until confirmed in writing."],["Ecological guidance","Website content and Prach provide general guidance. Site-specific decisions require an assessment by appropriately qualified professionals."],["Orders and contracts","Adding an item to the cart creates an enquiry only. A purchase or project begins only after scope, pricing and terms are formally accepted."],["Responsible use","Do not submit unlawful, harmful or misleading content through website forms or portals."]] },
  delivery: { eyebrow: "Orders and delivery", title: "Living material needs more care than a standard parcel.", icon: PackageCheck, sections: [["Availability review","Every plant and product enquiry is checked for batch availability, order quantity, destination and timing."],["Suitability and provenance","Native-plant orders may require regional suitability and provenance review before confirmation."],["Delivery planning","Transport method, protection, unloading, planting window and site access are agreed in the quotation."],["Receiving plants","Inspect living material on arrival and follow the agreed handling, watering and planting instructions."]] },
} as const;

export function InformationPage({ kind }: { kind: keyof typeof content }) {
  const page = content[kind]; const Icon = page.icon;
  return <main><section className="page-hero policy-hero"><div className="shell"><span className="policy-icon"><Icon/></span><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p>Last reviewed 19 July 2026</p></div></section><section className="section"><div className="shell policy-content">{page.sections.map(([title,copy]) => <section key={title}><h2>{title}</h2><p>{copy}</p></section>)}<div className="suitability-note"><Leaf/><div><b>Need clarification?</b><p>Use the contact page and include the relevant enquiry or order reference.</p><a href="/contact">Contact Prachurja <ArrowRight/></a></div></div></div></section></main>;
}
