export type NurseryPlant = {
  id: string;
  commonName: string;
  botanicalName: string;
  region: string;
  ecologicalRole: string;
  waterRequirement: "Low" | "Moderate" | "High";
  plantSize: string;
  price: number;
  stockStatus: "Available" | "Low stock" | "Contract grow";
  imageUrl: string;
  description: string;
  featured: boolean;
  active: boolean;
  sortOrder: number;
};

export type NurseryCartItem = {
  id: string;
  commonName: string;
  botanicalName: string;
  unitPrice: number;
  quantity: number;
  imageUrl: string;
};

export const fallbackPlants: NurseryPlant[] = [
  { id: "neem", commonName: "Neem", botanicalName: "Azadirachta indica", region: "Central and peninsular India", ecologicalRole: "Drought-tolerant canopy", waterRequirement: "Low", plantSize: "60–90 cm", price: 145, stockStatus: "Available", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Neem_Tree_in_Rajasthan%2C_India.jpg/330px-Neem_Tree_in_Rajasthan%2C_India.jpg", description: "A hardy native tree for suitable dry and mixed restoration settings.", featured: true, active: true, sortOrder: 1 },
  { id: "arjun", commonName: "Arjun", botanicalName: "Terminalia arjuna", region: "Riverine plains", ecologicalRole: "Riverbank and riparian structure", waterRequirement: "High", plantSize: "75–100 cm", price: 190, stockStatus: "Available", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/94/Fruit_I_IMG_9577.jpg", description: "A river-associated native tree for locally suitable riparian sites.", featured: true, active: true, sortOrder: 2 },
  { id: "jamun", commonName: "Jamun", botanicalName: "Syzygium cumini", region: "Tropical and subtropical India", ecologicalRole: "Food and habitat for wildlife", waterRequirement: "Moderate", plantSize: "60–90 cm", price: 175, stockStatus: "Available", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Syzygium_cumini_Bra30.png", description: "A fruiting native tree for suitable moist and riparian settings.", featured: true, active: true, sortOrder: 3 },
  { id: "mahua", commonName: "Mahua", botanicalName: "Madhuca longifolia", region: "Central Indian dry forests", ecologicalRole: "Community livelihood and habitat", waterRequirement: "Low", plantSize: "45–60 cm", price: 210, stockStatus: "Low stock", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/61/Mahuwa_trees_in_Chhattisgarh.jpg", description: "A culturally important native tree for appropriate dry forest landscapes.", featured: false, active: true, sortOrder: 4 },
  { id: "amla", commonName: "Amla", botanicalName: "Phyllanthus emblica", region: "Dry deciduous zones", ecologicalRole: "Agroforestry and seasonal food", waterRequirement: "Low", plantSize: "45–75 cm", price: 160, stockStatus: "Available", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Phyllanthus_officinalis.jpg", description: "A native fruit tree suited to locally appropriate farm and restoration systems.", featured: false, active: true, sortOrder: 5 },
  { id: "banyan", commonName: "Banyan", botanicalName: "Ficus benghalensis", region: "Most Indian plains", ecologicalRole: "Keystone canopy and wildlife habitat", waterRequirement: "Moderate", plantSize: "60–90 cm", price: 280, stockStatus: "Contract grow", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Great_banyan_tree_kol.jpg", description: "A large-canopy native Ficus for sites with adequate long-term space.", featured: false, active: true, sortOrder: 6 },
  { id: "peepal", commonName: "Peepal", botanicalName: "Ficus religiosa", region: "Plains and lower hills", ecologicalRole: "Wildlife-supporting Ficus", waterRequirement: "Moderate", plantSize: "60–90 cm", price: 240, stockStatus: "Low stock", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/94/Ficus_religiosa_Bo.jpg", description: "A native Ficus with important habitat value where it belongs locally.", featured: false, active: true, sortOrder: 7 },
  { id: "palash", commonName: "Palash", botanicalName: "Butea monosperma", region: "Dry deciduous India", ecologicalRole: "Pollinator-supporting tree", waterRequirement: "Low", plantSize: "45–75 cm", price: 185, stockStatus: "Available", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/38/STS_001_Butea_monosperma.jpg", description: "A flowering native tree associated with dry deciduous landscapes.", featured: false, active: true, sortOrder: 8 },
  { id: "kadamba", commonName: "Kadamba", botanicalName: "Neolamarckia cadamba", region: "Moist tropical India", ecologicalRole: "Fast early canopy", waterRequirement: "High", plantSize: "75–100 cm", price: 195, stockStatus: "Available", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Neolamarckia_cadamba_6226.jpg", description: "A fast-growing native tree for suitable warm, moist sites.", featured: false, active: true, sortOrder: 9 },
  { id: "karanj", commonName: "Karanj", botanicalName: "Millettia pinnata", region: "Coasts and river systems", ecologicalRole: "Pioneer and nitrogen-fixing tree", waterRequirement: "Moderate", plantSize: "60–90 cm", price: 155, stockStatus: "Available", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Pongamia_pinnata_%28Karanj%29_near_Hyderabad_W_IMG_7633.jpg", description: "A potential pioneer for suitable local conditions and restoration objectives.", featured: false, active: true, sortOrder: 10 },
  { id: "tendu", commonName: "Tendu", botanicalName: "Diospyros melanoxylon", region: "Central Indian forests", ecologicalRole: "Dry-forest understorey", waterRequirement: "Low", plantSize: "30–45 cm", price: 170, stockStatus: "Contract grow", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Bark_of_Diospyros_melanoxylon.jpg", description: "A native dry-forest species supplied through planned contract growing.", featured: false, active: true, sortOrder: 11 },
  { id: "sal", commonName: "Sal", botanicalName: "Shorea robusta", region: "Northern and central moist forests", ecologicalRole: "Long-lived canopy tree", waterRequirement: "Moderate", plantSize: "45–60 cm", price: 230, stockStatus: "Contract grow", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Shorea_robusta.jpg", description: "A major native canopy species within its natural forest range.", featured: false, active: true, sortOrder: 12 },
  { id: "khair", commonName: "Khair", botanicalName: "Senegalia catechu", region: "Dry forests and foothills", ecologicalRole: "Soil-stabilising pioneer", waterRequirement: "Low", plantSize: "45–60 cm", price: 150, stockStatus: "Available", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Acacia_catechu_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-003.jpg", description: "A native pioneer for suitable dry, stony and erosion-prone sites.", featured: false, active: true, sortOrder: 13 },
  { id: "shisham", commonName: "Shisham", botanicalName: "Dalbergia sissoo", region: "Indo-Gangetic riverine belt", ecologicalRole: "Riverine pioneer tree", waterRequirement: "Moderate", plantSize: "60–90 cm", price: 180, stockStatus: "Available", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Dalbergia_sissoo_Bra24.png", description: "A native riverine species for sites within its ecological range.", featured: false, active: true, sortOrder: 14 },
  { id: "baheda", commonName: "Baheda", botanicalName: "Terminalia bellirica", region: "Moist deciduous India", ecologicalRole: "Canopy and bird habitat", waterRequirement: "Moderate", plantSize: "60–90 cm", price: 205, stockStatus: "Low stock", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/Terminalia_bellirica.jpg", description: "A native Terminalia for suitable moist deciduous restoration systems.", featured: false, active: true, sortOrder: 15 },
  { id: "harad", commonName: "Harad", botanicalName: "Terminalia chebula", region: "Sub-Himalayan and deciduous belts", ecologicalRole: "Diverse native canopy", waterRequirement: "Moderate", plantSize: "45–75 cm", price: 215, stockStatus: "Contract grow", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Harra_%28Terminalia_chebula%29_leafless_tree_at_23_Mile%2C_Duars%2C_WB_W_IMG_5905.jpg", description: "A native deciduous tree supplied for regionally appropriate planting plans.", featured: false, active: true, sortOrder: 16 },
  { id: "kusum", commonName: "Kusum", botanicalName: "Schleichera oleosa", region: "Central and eastern India", ecologicalRole: "Wildlife-supporting canopy", waterRequirement: "Low", plantSize: "45–60 cm", price: 225, stockStatus: "Available", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Schleic_oleos_080320-5971_rgn.JPG", description: "A native tree for suitable central and eastern Indian landscapes.", featured: false, active: true, sortOrder: 17 },
  { id: "bamboo", commonName: "Male Bamboo", botanicalName: "Dendrocalamus strictus", region: "Dry deciduous India", ecologicalRole: "Soil cover and slope stability", waterRequirement: "Low", plantSize: "60–90 cm", price: 135, stockStatus: "Available", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/52/Bamboo_leaves1.JPG", description: "A clumping native bamboo for suitable dry deciduous settings.", featured: false, active: true, sortOrder: 18 },
  { id: "putranjiva", commonName: "Putranjiva", botanicalName: "Putranjiva roxburghii", region: "Moist deciduous plains", ecologicalRole: "Bird-supporting evergreen", waterRequirement: "Moderate", plantSize: "45–75 cm", price: 200, stockStatus: "Low stock", imageUrl: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Putranjiva_roxburghii_01.JPG?width=1000", description: "A native evergreen for locally appropriate moist-deciduous planting.", featured: false, active: true, sortOrder: 19 },
  { id: "kanak-champa", commonName: "Kanak Champa", botanicalName: "Pterospermum acerifolium", region: "Eastern and northeastern India", ecologicalRole: "Flowering pollinator tree", waterRequirement: "Moderate", plantSize: "60–90 cm", price: 260, stockStatus: "Contract grow", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Kanak_Champa_%28Pterospermum_acerifolium%29_in_Hyderabad_W_IMG_7126.jpg", description: "A flowering native tree for suitable eastern and northeastern sites.", featured: false, active: true, sortOrder: 20 },
];
